general_config:
  model_type: VisionBitformerForImageClassification
  num_labels: !!int 10

model_config:
  vocab_size: !!int 32000
  hidden_size: !!int 28
  intermediate_size: !!int 512
  num_hidden_layers: !!int 1
  num_attention_heads: !!int 2
  num_key_value_heads: !!int 2
  hidden_act: !!str silu
  max_position_embeddings: !!int 4096
  initializer_range: !!float 0.02
  rms_norm_eps: !!float 1e-5
  use_cache: false
  pad_token_id: null
  bos_token_id: 1
  eos_token_id: 2
  tie_word_embeddings: false
  rope_theta: !!float 1e6
  sliding_window: !!int 4096
  attention_dropout: !!float 0.0
  num_experts_per_tok: !!int 2
  num_local_experts: !!int 4
  output_router_logits: true
  router_aux_loss_coef: !!float 0.001
  is_causal: false
  moe: true
  bitnet: false

training_args:
  # typical args
  output_dir: !!str ./results
  logging_dir: !!str ./logs
  report_to: null
  evaluation_strategy: !!str epoch
  per_device_train_batch_size: !!int 64
  per_device_eval_batch_size: !!int 64
  gradient_accumulation_steps: !!int 1
  learning_rate: !!float 0.0005
  weight_decay: !!float 0.01
  num_train_epochs: !!int 10
  warmup_ratio: !!float 0.0
  warmup_steps: !!int 100
  lr_scheduler_type: !!str cosine
  save_strategy: !!str epoch
  save_steps: !!int 500
  save_total_limit: !!int 2
  dataloader_drop_last: false
  eval_steps: null
  dataloader_num_workers: !!int 0
  logging_strategy: steps
  logging_first_step: false
  logging_steps: !!int 500
  bf16: false
  fp16: false
  seed: !!int 42
  adam_beta1: !!float 0.9
  adam_beta2: !!float 0.999
  adam_epsilon: !!float 1e-08
  max_grad_norm: !!float 1.0
  do_train: true
  do_eval: true
  do_predict: false
  eval_accumulation_steps: null
  group_by_length: false
  length_column_name: !!str length
  save_safetensors: true
  optim: !!str adamw_torch
  
  # less typical
  eval_delay: 0
  max_steps: -1
  overwrite_output_dir: false
  prediction_loss_only: false
  lr_scheduler_kwargs: null
  log_level: passive
  log_level_replica: warning
  log_on_each_node: true
  logging_nan_inf_filter: true
  fp16_opt_level: O1
  half_precision_backend: auto
  bf16_full_eval: false
  fp16_full_eval: false
  per_gpu_train_batch_size: null
  per_gpu_eval_batch_size: null
  tf32: null
  local_rank: -1
  ddp_backend: null
  tpu_num_cores: null
  tpu_metrics_debug: false
  debug: ''
  save_on_each_node: false
  save_only_model: false
  no_cuda: false
  use_cpu: false
  use_mps_device: false
  data_seed: null
  jit_mode_eval: false
  use_ipex: false
  dataloader_prefetch_factor: null
  past_index: -1
  run_name: null
  disable_tqdm: null
  remove_unused_columns: true
  label_names: null
  load_best_model_at_end: true
  metric_for_best_model: accuracy
  greater_is_better: true
  ignore_data_skip: false
  fsdp: ''
  fsdp_min_num_params: 0
  fsdp_config: null
  fsdp_transformer_layer_cls_to_wrap: null
  accelerator_config: null
  deepspeed: null
  label_smoothing_factor: 0.0
  optim_args: null
  adafactor: false
  ddp_find_unused_parameters: null
  ddp_bucket_cap_mb: null
  ddp_broadcast_buffers: null
  dataloader_pin_memory: true
  dataloader_persistent_workers: false
  skip_memory_metrics: true
  use_legacy_prediction_loop: false
  push_to_hub: false
  resume_from_checkpoint: null
  hub_model_id: null
  hub_strategy: every_save
  hub_token: null
  hub_private_repo: false
  hub_always_push: false
  gradient_checkpointing: false
  gradient_checkpointing_kwargs: null
  include_inputs_for_metrics: false
  fp16_backend: auto
  push_to_hub_model_id: null
  push_to_hub_organization: null
  push_to_hub_token: null
  mp_parameters: ''
  auto_find_batch_size: false
  full_determinism: false
  torchdynamo: null
  ray_scope: last
  ddp_timeout: 1800
  torch_compile: false
  torch_compile_backend: null
  torch_compile_mode: null
  dispatch_batches: null
  split_batches: null
  include_tokens_per_second: null
  include_num_input_tokens_seen: null
  neftune_noise_alpha: null